# This is a basic workflow that is manually triggered

name: Publish Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  release:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Build Release
      ##run: echo "Hello ${{ github.event.inputs.name }}"
      run: dotnet pack -c Release
    - name: Pack and Publish
      run: dotnet pack -c Relaase -o out
    - name: Publish to Nuget 
    - run: dotnet nuget push /out/*.nupkg  --skip-duplicate --api-key ${{ secrets.nugetkey }} --source https://api.nuget.org/v3/index.json
 
